### ISSUE TITLE
Proposal: Introduce yocto release branches for backwards compatibility

### ISSUE THREAD

**Issue by kkettinger** [slint-ui/meta-slint#5]
My propsal is to intruduce yocto release branches (e.g. krikstone, mickledore) for backwards compatibility. When someone is using kirkstone, there are no surprises when meta-slint upgrades to a new yocto version.

Yocto release names can be found here: https://wiki.yoctoproject.org/wiki/Releases

**Comment by tronical** [comment]
I think that makes sense to introduce when a divergence happens. Ideally master is usable with multiple yocto versions. But I guess that won't work for very long.

Too bad GitHub Actions are not suitable for CI - I'm concerned that multiple branches increase the amount of effort to maintain.

**Comment by kkettinger** [comment]
You are right, as long as there is no deviation between the versions, extra branches just increase the amount of work to do. I was just feeling uneasy including master as branch into my manifest file 😄

**Comment by tronical** [comment]
I've switched `meta-slint` over to use `meta-rust-bin`, and I've added a CI that tests at least builds with kirkstone and scarthgap. I'll close this as not planned until other evidence arises that suggests that we should add branches.
