### ISSUE TITLE
slint-demos recipe error with package.rust-version

### ISSUE THREAD

**Issue by hiagofranco** [slint-ui/meta-slint#8]
Hello,

I'm unable to bitbake the `slint-demos` recipe due to this error:

```text
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: cargo = /home/kirkstone/bsp-6/build/tmp/work/cortexa53-mx8mp-tdx-linux/slint-demos/git-r0/recipe-sysroot-native/usr/bin/cargo
| NOTE: rustc =
| NOTE: cargo build -v --target aarch64-tdx-linux --release --manifest-path=/home/kirkstone/bsp-6/build/tmp/work/cortexa53-mx8mp-tdx-linux/slint-demos/git-r0/git//Cargo.toml --features slint/renderer-winit-skia -p energy-monitor -p slide_puzzle -p printerdemo -p gallery -p opengl_texture -p opengl_underlay
| error: failed to load manifest for workspace member `/home/kirkstone/bsp-6/build/tmp/work/cortexa53-mx8mp-tdx-linux/slint-demos/git-r0/git/api/cpp`
|
| Caused by:
|   failed to parse manifest at `/home/kirkstone/bsp-6/build/tmp/work/cortexa53-mx8mp-tdx-linux/slint-demos/git-r0/git/api/cpp/Cargo.toml`
|
| Caused by:
|   invalid type: map, expected a string for key `package.rust-version`
| WARNING: exit code 101 from a shell command.
ERROR: Task (/home/kirkstone/bsp-6/build/../layers/meta-slint/recipes-example/slint-demos/slint-demos_git.bb:do_compile) failed with exit code '1'
```

I'm not a Rust developer, so I don't know exactly what is going on. I can see this parameter is defined inside `api/cpp/Cargo.toml` with the workspace object:

```rust
rust-version.workspace = true
```

And here this is expecting a string. Can someone help me?

Thanks!

**Comment by tronical** [comment]
Thanks for the report. What version of Rust are you using in your build?

**Comment by hiagofranco** [comment]
I've just included the meta-rust master branch, so based on the recipe I should be using 1.71.

```bash
$ bitbake-layers show-recipes | grep -C 4 ^rust
  meta-networking      0.36
run-postinsts:
  meta                 1.0
rust:
  meta-rust            1.66.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta-rust            1.66.1 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta-rust            1.71.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta                 1.59.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
rust-cross-canadian-aarch64:
  meta-rust            1.71.0
  meta                 1.59.0
  meta-rust            1.66.1
  meta-rust            1.66.0
rust-cross-cortexa53-glibc:
  meta-rust            1.71.0
  meta                 1.59.0
  meta-rust            1.66.0
  meta-rust            1.66.1
rust-crosssdk-x86_64-glibc:
  meta                 1.59.0
rust-hello-world:
  meta-rust            git
  meta                 git
rust-llvm:
  meta                 1.59.0
  meta-rust            1.66.1
  meta-rust            1.71.0
  meta-rust            1.66.0
rust-native:
  meta                 1.59.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta-rust            1.66.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta-rust            1.66.1 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
  meta-rust            1.71.0 (skipped: Rust recipe doesn't work for target builds at this time. Fixes welcome.)
rust-tools-cross-canadian-aarch64:
  meta-rust            1.71.0
  meta                 1.59.0
  meta-rust            1.66.1
  meta-rust            1.66.0
rustfmt:
  meta-rust            1.4.2
rwmem:
  meta-oe              1.2+gitAUTOINC+3ec3e42121_4b10c65405

**Comment by tronical** [comment]
Yeah I think that looks good. Could you try running /home/kirkstone/bsp-6/build/tmp/work/cortexa53-mx8mp-tdx-linux/slint-demos/git-r0/recipe-sysroot-native/usr/bin/cargo --version ?

I'll try to reproduce this tomorrow.

**Comment by hiagofranco** [comment]
Sure, here is the output:

```text
cargo 1.59.0
```

> I'll try to reproduce this tomorrow.

All right, thanks for the help!

**Comment by ogoffart** [comment]
Workspace settings inheritance was only implemented in Rust 1.64.0. hence the error.

Our CMake scripts should normaly have ensured that you have at least Rust 1.66
But I realize that our demos probably don't use cmake.

**Comment by tronical** [comment]
I wonder if for your 1.59 is chosen because of that odd entry in tcmode-default.conf in poky. I see warnings about 1.59, but my build chooses 1.71.0 regardless, but somehow yours picks an old version of cargo/rust.

Could you try adding `RUSTVERSION = "1.71.0"` to your `local.conf`?

For me that did the trick of removing the warnings.

**Comment by hiagofranco** [comment]
Thank you now it works! My image finished successfully. I don't know exactly why this happened, could be something on my side, I will further investigate and let you guys know. Anyways, this issue can be closed.

Just as information, I got some Warnings:

```text
WARNING: slint-demos-git-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPLv3 [obsolete-license]
WARNING: slint-demos-git-r0 do_package_qa: QA Issue: slint-demos: recipe doesn't inherit features_check [unhandled-features-check]
WARNING: tdx-reference-multimedia-image-1.0-r0 do_rootfs: QA Issue: The license listed Slint-Commercial was not in the licenses collected for recipe slint-demos [license-file-missing]
```
just minor warnings, nothing urgent or anything like that.

Again, thanks for the fast reply! I will test it now on Toradex hardware with our Yocto images.

**Comment by tronical** [comment]
Thanks. Let us know how it goes.

Yeah, the recipes still need a bit of work - on the warning side as well as functionality. For the Slint-cpp recipe for example we currently only support the C++ interpreter API. For supporting the slint compilation to C++ we need to figure out how to let one bit bake build produces artefacts for the host _and_ the target at the same time.

Do you know if that's somehow possible?

**Comment by hiagofranco** [comment]
> Thanks. Let us know how it goes.

Sure, I don't have the hardware today, so I'll probably test it on Monday. It's not something urgent or something like that, I was just curious to see how it works.

> Do you know if that's somehow possible?

Actually, I don't know, sorry. I will take a look later and I can report any improvements that I might see here Overall, I'm still learning Yocto.

**Comment by hiagofranco** [comment]
Hi @tronical, just an update:

printerdemo and energy-monitor give me a segmentation fault.
slide_puzzle does nothing for me.
The rest, like the OpenGL demos, works fine.

I just wanted to give this update, maybe you could look into that in the future. Again, this is not something urgent or anything like that, I was curious to see if the layer would work with our images.

I've used the Toradex Verdin iMX8M Plus with a DSI to LVDS capacitive touch display for this test, running Weston on the downstream kernel.

Thanks

**Comment by tronical** [comment]
Thanks for checking. Odd that they crash. Do you see any error messages or just “Segmentation fault”?

**Comment by hiagofranco** [comment]
Just the Segmentation Fault message. Maybe I'm missing something on my side, but I'm not sure.

**Comment by tronical** [comment]
Hm just a segmentation fault sounds like some OpenGL driver crash. Before Slint crashes it usually panics with a message. If you’re interested in digging further you could run it through gdb.

I’ve seen this symptom when running on qemu, but that’s not quite your setup.
